---

# Dependências PIP 

docker__pip_dependencies:
  - "gcc"
  - "python3-setuptools"
  - "python3-dev"
  - "python3-pip"
  - "virtualenv"

# Dependências DOcker        

docker__package_dependencies:
  - "apt-transport-https"
  - "ca-certificates"
  - "cron"
  - "gnupg2"
  - "curl"
  - "software-properties-common"

#pip packages
docker__default_pip_packages:
  - name: "docker"
    state: "{{ docker__pip_docker_state }}"
docker__pip_docker_state: "present"
    
docker__pip_packages: []

# Criar containers

create_containers: 1
default_container_name: app_docker-desafio
default_container_image: 172.17.0.5:5000/desafio_prod
default_container_command: sleep 1d

MAX_CPU: 1
MAX_MEMORY: 1024m
PORT: "8080"
APP_PORT: "8080"


# Verão Docker

docker__edition: "ce"
docker__channel: ["stable"]
docker__version: ""
docker__state: "present"

# Repositório 

docker__architecture_map:
 "x86_64": "amd64"
 "aarch": "arm64"
 "armhf": "armhf"
 "armv7l": "armhf"

docker__apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker__apt_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker__apt_repository: >
  deb [arch={{ docker__architecture_map[ansible_architecture] }}]
  https://download.docker.com/linux/{{ ansible_distribution | lower }}
  {{ ansible_distribution_release }} {{ docker__channel | join ('') }}
...

